### ISSUE TITLE
Errors in Script

### ISSUE THREAD

**Issue by maddempsey** [Merola132/ADxRay#1]
Hello, was looking forward in running this script on my lab DC but encountered these errors:  Did I forget to do something?

Mike D.

[Issues.txt](https://github.com/ClaudioMerola/ADxRay/files/6141083/Issues.txt)

**Comment by ClaudioMerola** [comment]
Hello, 

Thanks for the feedback.

This error was because of the following line:

$Backup = $Backup.tostring(“MM-dd-yyyy”)

The issue were because the quotes ASCI characters were wrong.

I fixed it and the newest version of the script should work fine.

Thanks
